heat_template_version: 2016-04-08
description: Deployment of MariaDB as single Node or Galera-CLuster with a flexible number of nodes. 

parameters:

  image_id:
    type: string
    description: Image used for servers
    default: ubuntu-xenial-16.04_softwareconfig_0.0.2
  key_name:
    type: string
    description: SSH key to connect to the servers
  flavor:
    type: string
    description: flavor used by the servers
    default: gp1.small
  availability_zone:
    type: string
    description: Availability Zone of the nodes.
    default: zone00
  resource_name:
    type: string
    description: Name-prefix for created resources in OpenStack.

  primary_volume_id:
    type: string
    description: ID of the pre-created volume to be attached to the primary node.
  primary_port:
    type: string
    description: Port-ID of the pre-created Port for the primary node.
  primary_ip:
    type: string
    description: IP of primary node.

  secondary_number:
    type: number
    description: number of secondarys
    default:  0
  secondary_volume_ids:
    type: comma_delimited_list
    description: ID of the pre-created volume to be attached to the secondary node.
    default: []
  secondary_ports:
    type: comma_delimited_list
    description: Network-Port used by the standby node.
    default: []
  secondary_ips:
    type: comma_delimited_list
    description: IP of  secondary node .
    default: []

  service_db:
    type: string
    description: Name of the Database.
    default: servicedb
  admin_user:
    type: string
    description: Admin user for the service.
    default: servicedb
  admin_password:
    type: string
    hidden: true
    description: Password for the service_user password.
    

resources:
  anti-affinity:
    type: OS::Nova::ServerGroup
    properties:
      name:
        str_replace:
          template: $resource_name-SG
          params:
            $resource_name: { get_param: resource_name }
      policies: [ 'anti-affinity' ]

  maria_prim_server:
    type: primary.yaml
    properties:
      primary_hostname:
        str_replace:
          template: $hostname-m0
          params:
            $hostname: { get_param: resource_name }
      image_id: {get_param: image_id }
      key_name: {get_param: key_name }
      flavor: {get_param: flavor }
      availability_zone: {get_param: availability_zone }
      service_db: {get_param: service_db }
      admin_user: {get_param: admin_user }
      admin_password: {get_param: admin_password }
      primary_port: {get_param: primary_port }
      primary_ip: {get_param: primary_ip }
      primary_volume_id: {get_param: primary_volume_id }
      server_group: {get_resource: anti-affinity}
      secondary_number: { get_param: secondary_number }
      secondary_ips: {get_param: secondary_ips }

  maria_sec_server:
    type: OS::Heat::ResourceGroup
    depends_on: maria_prim_server
    properties:
      count: { get_param: secondary_number }
      resource_def:
        type: secondaries.yaml
        properties:
          secondary_hostname:
            str_replace:
              template: $hostname-s%index%
              params:
                 $hostname: { get_param: resource_name }
          image_id: {get_param: image_id }
          key_name: {get_param: key_name }
          flavor: {get_param: flavor }
          availability_zone: {get_param: availability_zone }
          service_db: {get_param: service_db }
          admin_user: {get_param: admin_user }
          admin_password: {get_param: admin_password }
          secondary_ports: {get_param: secondary_ports }
          primary_ip: {get_param: primary_ip }
          server_group: {get_resource: anti-affinity}
          secondary_volume_ids: {get_param: secondary_volume_ids }
          secondary_ips: {get_param: secondary_ips }
          secondary_index: 0%index%
