---
name: osb-mariadb

releases:
- name: osb-bosh-mysql
  version: latest
- name: prometheus
  version: latest
- name: osb-bosh-haproxy
  version: latest

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

update:
  canaries: 1
  canary_watch_time: 10000-600000
  update_watch_time: 10000-600000
  max_in_flight: 1
  serial: true

instance_groups:
- name: mysql
  instances: 3
  networks:
  - name: service
  azs:
  - z1
  vm_type: minimal
  stemcell: default
  jobs:
  - name: mysql
    release: osb-bosh-mysql
  - name: backup-agent
    release: osb-bosh-mysql
  - name: mysqld_exporter
    release: prometheus
    properties:
      mysqld_exporter:
        mysql:
          address: localhost
          username: ((exporter_credentials.username))
          password: ((exporter_credentials.password))
  properties:
    backup_agent:
      username: backup
      password: rulez
    mysql:
      admin_users:
      - username: root
        password: rulez
        remote_access: true
      - username: exporter
        password: rulez
        remote_access: true
      backup_users:
      - username: backup
        password: rulez
        remote_access: true
      users:
      - username: sample
        password: rulez
        remote_access: true
      databases: []

- name: haproxy
  instances: 1
  vm_type: minimal
  stemcell: default
  networks:
  - name: service
  azs:
  - z1
  jobs:
  - name: haproxy
    release: osb-bosh-haproxy
  - name: haproxy_exporter
    release: prometheus
    properties:
      haproxy_exporter:
        haproxy:
          scrape_uri: "unix:/var/vcap/sys/run/haproxy/stats.sock"
  properties:
    ha_proxy:
      client_timeout: 10
      server_timeout: 10
      queue_timeout: 10
      binding_ip: 0.0.0.0
      disable_http: true
      backend_port: 3306
      stats_enable: true
      stats_user: admin
      stats_password: admin
      tcp:
      - name: mysql
        balance: roundrobin
        port: 3306
        check: "check"
