---
name: osb-mariadb

releases:
- name: osb-bosh-mysql
  version: latest
- name: osb-bosh-monitoring
  version: latest
- name: osb-bosh-haproxy
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  canary_watch_time: 10000-600000
  update_watch_time: 10000-600000
  max_in_flight: 1
  serial: true

instance_groups:
- name: mariadb
  instances: 3
  networks:
  - name: service
  azs:
  - z1
  vm_type: minimal
  stemcell: default
  jobs:
  - name: mysql
    release: osb-bosh-mysql
  - name: node_exporter
    release: osb-bosh-monitoring
  - name: mysqld_exporter
    release: osb-bosh-monitoring
  properties:
    mysqld_exporter:
      login: root
    mysql:
      remote_admin_access: true
      admin_username: root

- name: haproxy
  instances: 1
  vm_type: minimal
  stemcell: default
  azs:
  - z1
  networks:
  - name: service
  jobs:
  - name: haproxy
    release: osb-bosh-haproxy
  - name: node_exporter
    release: osb-bosh-monitoring
  - name: haproxy_exporter
    release: osb-bosh-monitoring
  properties:
    ha_proxy:
      client_timeout: 10
      server_timeout: 10
      queue_timeout: 10
      binding_ip: 0.0.0.0
      disable_http: true
      backend_port: 3306
      stats_enable: true
      stats_user: admin
      stats_password: admin
      tcp:
      - name: mysql
        balance: roundrobin
        port: 3306
        check: "check"
